# Dockerfile.prod
FROM wordpress:latest

COPY . /var/www/html

# Install additional dependencies if needed
RUN apt-get update && apt-get install -y less

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*